ALTER TABLE "Trip" ADD COLUMN "mobilityProfile" TEXT NOT NULL DEFAULT 'STANDARD';
ALTER TABLE "Trip" ADD COLUMN "avoidStairs" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Trip" ADD COLUMN "shadePriority" TEXT NOT NULL DEFAULT 'MEDIUM';
