import { useCallback, useEffect, useState } from 'react';
import { Image, Pressable, StyleSheet, View } from 'react-native';
import { useLocalSearchParams, useRouter } from 'expo-router';
import { useAuth } from '@/auth/AuthProvider';
import { Button } from '@/components/Button';
import { Screen } from '@/components/Screen';
import { TabBar } from '@/components/TabBar';
import { Text } from '@/components/Text';
import { color, radius, spacing } from '@/design/tokens';
import { loadRecommendationResult, type RecommendationCourse, type RecommendationViewModel, unavailableRecommendations } from '@/plan/recommendations';

const STATUS = { VERIFIED: '확인됨', ESTIMATED: '추정', UNKNOWN: '미확인' } as const;
const CROWD = { LOW: '여유', MEDIUM: '보통', HIGH: '혼잡' } as const;
const FALLBACK = { MODEL: '개인화 추천', RULE: '조건 기반 추천', BASELINE: '기본 추천' } as const;

function CourseCard({ course, onAction }: { course: RecommendationCourse; onAction: (state: RecommendationCourse['actionState']) => void }) {
  return <View style={styles.card}>{course.imageUrl ? <Image source={{ uri: course.imageUrl }} accessibilityLabel={`${course.title} 대표 이미지`} resizeMode="cover" style={styles.image} /> : <View accessibilityLabel="대표 이미지 없음" style={styles.imageFallback}><Text variant="caption" color={color.text.muted}>이미지 정보 없음</Text></View>}<View style={styles.cardBody}><View style={styles.titleRow}><Text variant="title" weight="bold" style={styles.grow}>{course.title}</Text><View style={styles.status}><Text variant="caption" weight="bold">{STATUS[course.dataStatus]}</Text></View></View><View style={styles.tags}>{course.reasons.map((reason, index) => <View key={`${reason}-${index}`} style={styles.tag}><Text variant="caption" weight="bold" color={color.brand.orange}>#{reason}</Text></View>)}</View><Text variant="caption" color={color.text.body}>예상 비용 · {course.estimatedCostKrw == null ? '미확인' : `${course.estimatedCostKrw.toLocaleString()}원`}</Text><Text variant="caption" color={color.text.body}>혼잡도 · {course.crowdLevel ? CROWD[course.crowdLevel] : '미확인'}</Text><Text variant="caption" color={course.mobilityWarnings?.length ? color.state.danger : color.text.body}>이동 제약 · {course.mobilityWarnings?.join(' · ') || '확인된 경고 없음'}</Text><Text variant="caption" color={color.text.muted}>{FALLBACK[course.fallbackMode]}</Text><View style={styles.actions}><Pressable accessibilityRole="button" accessibilityState={{ selected: course.actionState === 'saved', busy: course.actionState === 'saving' }} onPress={() => onAction(course.actionState === 'saved' ? 'idle' : 'saved')} style={styles.action}><Text variant="caption" weight="bold">{course.actionState === 'saved' ? '저장됨' : '저장'}</Text></Pressable><Pressable accessibilityRole="button" accessibilityState={{ selected: course.actionState === 'excluded', busy: course.actionState === 'excluding' }} onPress={() => onAction(course.actionState === 'excluded' ? 'idle' : 'excluded')} style={styles.action}><Text variant="caption" weight="bold">{course.actionState === 'excluded' ? '제외됨' : '제외'}</Text></Pressable></View></View></View>;
}

export default function Recommendations() {
  const router = useRouter(); const { accessToken } = useAuth(); const { id, jobId } = useLocalSearchParams<{ id: string; jobId?: string }>();
  const [view, setView] = useState<RecommendationViewModel>(() => jobId ? { ...unavailableRecommendations(), state: 'loading', message: '추천 결과를 확인하고 있어요.' } : unavailableRecommendations());
  const reload = useCallback(async () => {
    if (!jobId) { setView(unavailableRecommendations()); return; }
    setView((current) => ({ ...current, state: 'loading', message: '추천 결과를 확인하고 있어요.' }));
    setView(await loadRecommendationResult(jobId, accessToken));
  }, [accessToken, jobId]);
  useEffect(() => { void reload(); }, [reload]);
  const updateAction = (courseId: string, actionState: RecommendationCourse['actionState']) => setView((current) => ({ ...current, courses: current.courses.map((course) => course.id === courseId ? { ...course, actionState } : course) }));
  const unavailable = view.state === 'unavailable' || view.state === 'empty-conflict';
  return <View style={styles.shell}><Screen scroll wide style={styles.canvas}><View style={styles.nav}><Pressable accessibilityRole="button" accessibilityLabel="뒤로 가기" onPress={() => router.canGoBack() ? router.back() : router.replace('/plan/confirm')} style={styles.back}><Text variant="title">‹</Text></Pressable><View style={styles.dots}><View style={styles.dot} /><View style={styles.dot} /><View style={styles.activeDot} /></View></View><Text variant="caption" weight="bold" color={color.brand.orange}>추천 일정 요약</Text><Text variant="display" weight="bold" style={styles.heading}>{view.state === 'success' || view.state === 'partial' || view.state === 'fallback' ? `${view.courses.length}가지 코스를 골라봤어요.` : '추천 결과'}</Text>
      {view.state === 'loading' && <View accessibilityLiveRegion="polite" style={styles.stateCard}><Text variant="title" weight="bold">추천을 불러오고 있어요</Text><Text color={color.text.body}>확인된 결과만 표시합니다.</Text></View>}
      {(view.state === 'partial' || view.state === 'fallback') && <View style={styles.notice}><Text accessibilityRole="alert" variant="caption" weight="bold">{view.message}</Text></View>}
      {(view.state === 'error' || view.state === 'offline') && <View style={styles.stateCard}><Text variant="title" weight="bold">{view.state === 'offline' ? '인터넷 연결을 확인해 주세요' : '추천을 불러오지 못했어요'}</Text><Text color={color.text.body}>{view.message}</Text><Button accessibilityRole="button" label="다시 시도" variant="ghost" onPress={() => void reload()} /></View>}
      {unavailable && <View style={styles.stateCard}><View style={styles.emptyMark}><Text variant="display">⌁</Text></View><Text variant="title" weight="bold">{view.state === 'empty-conflict' ? '조건을 만족하는 코스가 없어요' : '아직 생성된 추천이 없어요'}</Text><Text color={color.text.body}>{view.message}</Text>{view.conflicts.map((item) => <Text key={item} accessibilityRole="alert" variant="caption" color={color.state.danger}>• {item}</Text>)}<Button accessibilityRole="button" label="조건 수정하기" variant="ghost" onPress={() => router.push('/plan/confirm')} />{jobId && <Button accessibilityRole="button" label="다시 확인" variant="ghost" onPress={() => void reload()} />}</View>}
      <View style={styles.list}>{view.courses.map((course) => <CourseCard key={course.id} course={course} onAction={(state) => updateAction(course.id, state)} />)}</View>
      <Button accessibilityRole="button" accessibilityState={{ disabled: !view.itineraryId }} label="이 일정으로 보기" disabled={!view.itineraryId} containerStyle={styles.cta} onPress={() => { if (view.itineraryId) router.push(`/${view.itineraryId}/result`); }} />
      {!view.itineraryId && <Text variant="caption" color={color.text.muted} style={styles.reason}>완성된 일정이 생기면 상세 일정으로 이동할 수 있어요.</Text>}
      <Text variant="caption" color={color.text.muted} style={styles.tripRef}>여행 {id || '미확인'}</Text>
    </Screen><TabBar active="schedule" /></View>;
}
const styles = StyleSheet.create({ shell: { flex: 1, backgroundColor: color.brand.ivory }, canvas: { backgroundColor: color.brand.ivory }, nav: { minHeight: 44, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' }, back: { width: 44, height: 44, borderRadius: radius.full, backgroundColor: color.surface.card, alignItems: 'center', justifyContent: 'center' }, dots: { flexDirection: 'row', gap: spacing[1] }, dot: { width: 6, height: 6, borderRadius: 3, backgroundColor: color.surface.field }, activeDot: { width: 18, height: 6, borderRadius: 3, backgroundColor: color.brand.orange }, heading: { marginTop: spacing[1], marginBottom: spacing[4] }, stateCard: { gap: spacing[3], padding: spacing[6], borderRadius: radius.lg, backgroundColor: color.surface.card, borderWidth: 1, borderColor: '#e8e4dd', alignItems: 'center' }, emptyMark: { width: 64, height: 64, borderRadius: radius.full, backgroundColor: '#ede9e0', alignItems: 'center', justifyContent: 'center' }, notice: { marginBottom: spacing[3], padding: spacing[3], borderRadius: radius.md, backgroundColor: color.state.warningBg }, list: { gap: spacing[3] }, card: { overflow: 'hidden', borderRadius: radius.lg, backgroundColor: color.surface.card, shadowColor: color.brand.navy, shadowOpacity: .08, shadowRadius: 12, elevation: 2 }, image: { width: '100%', height: 140 }, imageFallback: { width: '100%', height: 120, backgroundColor: '#ede9e0', alignItems: 'center', justifyContent: 'center' }, cardBody: { gap: spacing[2], padding: spacing[4] }, titleRow: { flexDirection: 'row', alignItems: 'center', gap: spacing[2] }, grow: { flex: 1 }, status: { paddingHorizontal: spacing[2], paddingVertical: spacing[1], borderRadius: radius.full, backgroundColor: color.surface.soft }, tags: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing[1] }, tag: { paddingHorizontal: spacing[2], paddingVertical: spacing[1], borderRadius: radius.sm, backgroundColor: color.surface.tint }, actions: { flexDirection: 'row', gap: spacing[2] }, action: { minWidth: 72, minHeight: 44, borderRadius: radius.sm, backgroundColor: '#f6f5f2', alignItems: 'center', justifyContent: 'center' }, cta: { minHeight: 50, marginTop: spacing[4], backgroundColor: color.brand.navy }, reason: { textAlign: 'center', marginTop: spacing[2] }, tripRef: { textAlign: 'center', marginTop: spacing[4] } });
