export type LegalSection = { title: [string, string]; paragraphs: [string, string][] };

export const TERMS_SECTIONS: LegalSection[] = [
  { title: ['1. 목적', '1. Purpose'], paragraphs: [['이 약관은 GABOLLE(가볼래)가 제공하는 여행 일정 추천 서비스 이용에 관한 회사와 이용자의 권리·의무 및 책임을 정합니다.', 'These Terms define the rights, obligations, and responsibilities between GABOLLE and users of its travel itinerary recommendation service.']] },
  { title: ['2. 계정과 연령 확인', '2. Accounts and age verification'], paragraphs: [['회원가입은 이메일·비밀번호 또는 Google·Kakao 계정으로 할 수 있으며, 가입 과정에서 연령 확인을 거칩니다. 가입 가능한 최소 연령은 팀 정책 확정 후 고지합니다.', 'You may sign up with email and password or a Google or Kakao account. Age verification is required. The minimum eligible age will be published after the team policy is finalized.']] },
  { title: ['3. 서비스 내용', '3. Service'], paragraphs: [['입력한 예산·기간·인원·취향·건강 및 식이 제약을 바탕으로 여행 일정을 생성하고 추천합니다. 추천 결과, 영업시간, 가격, 혼잡도는 실제 상황과 다를 수 있으므로 방문 전에 확인해 주세요.', 'We create and recommend itineraries using your budget, dates, party size, preferences, and health or dietary constraints. Recommendations, opening hours, prices, and congestion may differ from actual conditions; verify them before visiting.']] },
  { title: ['4. 이용자의 의무', '4. User responsibilities'], paragraphs: [['계정 도용, 서비스 운영 방해, 허위 정보 등록, 개인정보 무단 수집, 불법·유해 콘텐츠 게시, 사칭·명예훼손, 무단 영리 이용, 소스코드 역분석·복제·배포를 해서는 안 됩니다.', 'You must not misuse another account, disrupt the service, submit false information, collect personal data without permission, post illegal or harmful content, impersonate or defame others, exploit the service commercially without permission, or reverse-engineer, copy, or distribute its source code.']] },
  { title: ['5. 신고와 콘텐츠 처리', '5. Reports and content moderation'], paragraphs: [['피드 카드의 더보기(⋯) 메뉴 또는 기록 상세 화면의 신고 버튼에서 사유(개인정보 노출·불쾌한 내용·스팸·기타)를 선택해 신고할 수 있습니다. 위반 콘텐츠 신고가 접수되면 24시간 안에 검토를 시작하며, 위반이 확인되면 삭제하거나 계정 이용을 제한할 수 있습니다.', 'You can report content from the "⋯" menu on a feed card or the report button on a record’s detail screen by choosing a reason (privacy exposure, offensive content, spam, or other). We begin reviewing reported content within 24 hours and may remove violations or restrict accounts.']] },
  { title: ['6. 계정 및 데이터 삭제', '6. Account and data deletion'], paragraphs: [['마이페이지에서 계정 삭제를 요청할 수 있습니다. 관계 법령에 따른 보관 의무가 있는 정보를 제외한 개인정보는 탈퇴 시 지체 없이 파기합니다.', 'You may request account deletion from My Page. On withdrawal, personal data is deleted without delay except where retention is required by law.']] },
  { title: ['7. 서비스 중단과 책임', '7. Interruptions and liability'], paragraphs: [['점검·장애 등 부득이한 사유로 서비스를 일시 중단할 수 있습니다. 천재지변이나 이용자의 귀책사유 등 회사가 통제할 수 없는 사유와, 추천 정보를 바탕으로 한 이용자의 결정 결과에 대해서는 책임을 지지 않습니다.', 'The service may be temporarily suspended for maintenance, outages, or other unavoidable reasons. We are not liable for events beyond our control or for decisions users make based on recommendations.']] },
  { title: ['8. 약관 변경과 준거법', '8. Changes and governing law'], paragraphs: [['변경 시 적용일과 사유를 사전에 알립니다. 대한민국 법령에 따라 해석하며 관할 법원, 버전, 시행일, 사업자 정보와 문의처는 팀 확정 후 이 화면에 반영합니다.', 'We will announce the effective date and reason before changing these Terms. Korean law governs them. The court of jurisdiction, version, effective date, operator details, and contact information will be added after team confirmation.']] },
];

export const PRIVACY_SECTIONS: LegalSection[] = [
  { title: ['1. 수집하는 정보', '1. Data we collect'], paragraphs: [['계정 생성 시 이메일, 암호화된 비밀번호(자체 가입), 표시 이름, 서비스 언어, 연령 확인 여부·시각, 기기 식별자를 처리합니다. 생년월일 자체는 저장하지 않습니다.', 'For account creation, we process your email, hashed password (email signup only), display name, service language, age-verification status and time, and device identifier. We do not store your date of birth.'], ['여행 계획을 위해 예산·기간·인원·취향 등의 조건과 생성된 일정을 저장합니다. 행동 기반 개인화, 정밀 위치정보, 건강·식이 제약은 각각 별도 동의를 받은 경우에만 처리합니다.', 'For trip planning, we store conditions such as budget, dates, party size and preferences, plus generated itineraries. Behavioral personalization, precise location, and health or dietary constraints are processed only with separate consent.']] },
  { title: ['2. 수집 목적', '2. Why we use it'], paragraphs: [['회원 식별·인증, 여행 일정 생성·추천, 동의한 개인화 기능 제공, 관련 법적 의무 이행에 사용합니다.', 'We use data to identify and authenticate users, create and recommend itineraries, provide consented personalization, and meet legal obligations.']] },
  { title: ['3. 보유 및 파기', '3. Retention and deletion'], paragraphs: [['회원 탈퇴 시까지 보유하고 탈퇴 시 지체 없이 파기합니다. 법령상 별도 보관 의무가 있는 정보는 해당 기간 보관한 뒤 파기합니다.', 'We retain data until account deletion, then delete it without delay. Data subject to legal retention duties is deleted after the required period.']] },
  { title: ['4. 외부 서비스', '4. External services'], paragraphs: [['Google·Kakao 로그인에는 이메일과 외부 식별자가 전달됩니다. 지도·번역·기상 업체는 실제 연동 업체와 처리 항목이 확정될 때 이 방침을 갱신하고 필요한 동의를 받습니다.', 'Google and Kakao login involve an email and external identifier. We will update this policy and obtain any required consent when map, translation, and weather providers and their processed data are finalized.'], ['"메뉴판 읽기"에서 사진을 고르면, 그 사진이 글자를 읽기 위해 바깥의 문자 인식 서비스(SSAFY GMS 중계를 거쳐 OpenAI)로 한 번 전달됩니다. 사진은 저희 서버에 저장하지 않으며 글자를 읽은 뒤 사라집니다. 보내기 전에 촬영 위치 정보(EXIF)를 지웁니다. 이 기능은 로그인한 뒤 이용자가 직접 사진을 고를 때만 동작하고, 연동 업체가 바뀌면 이 방침을 먼저 갱신합니다.', 'When you choose a photo in "Read a menu," that photo is sent once to an outside text-recognition service (OpenAI, via the SSAFY GMS relay) so its text can be read. We do not store the photo on our servers; it is discarded after the text is read. Location data (EXIF) is removed before sending. This feature runs only when you are signed in and choose a photo yourself, and we will update this policy before changing providers.']] },
  { title: ['5. 이용자의 권리', '5. Your rights'], paragraphs: [['개인정보 열람·정정·삭제·처리정지를 요청할 수 있습니다. 계정 삭제는 마이페이지에서 요청할 수 있으며, 기타 요청을 위한 문의 창구는 팀 확정 후 안내합니다.', 'You may request access, correction, deletion, or restriction of your data. Account deletion is available in My Page; a contact channel for other requests will be published after team confirmation.']] },
  { title: ['6. 안전성 확보 조치', '6. Security'], paragraphs: [['비밀번호는 해시로 저장하고 인증 토큰에는 만료 시간을 적용합니다. 접근 권한 관리와 암호화 통신 등 구체적인 보호조치는 운영 환경 검증 후 갱신합니다.', 'Passwords are hashed and authentication tokens expire. Details of access control, encrypted transport, and other safeguards will be updated after production verification.']] },
  { title: ['7. 책임자와 시행일', '7. Privacy contact and effective date'], paragraphs: [['개인정보 보호책임자 이름·연락처·이메일, 방침 버전과 시행일은 팀 확정 후 이 화면에 반영합니다. 확정 전인 항목을 임의로 기재하지 않습니다.', 'The privacy officer name, contact details, policy version, and effective date will be added after team confirmation. We do not invent unconfirmed legal details.']] },
];

// 공공데이터포털에서 받는 두 API 모두 "공공저작물 자유이용허락 표시기준 제1유형"(출처표시) 라이선스다
// 상업적 이용·2차 저작물 제작은 자유롭지만 출처 표시가 조건이라 이 화면으로 표시한다후속).
export const DATA_SOURCES_SECTIONS: LegalSection[] = [
  { title: ['1. 날씨 정보', '1. Weather data'], paragraphs: [['"여행 준비" 화면의 기온·강수확률은 기상청 단기예보 조회서비스(공공데이터포털, data.go.kr)를 활용해 제공합니다.', 'Temperature and precipitation probability on the "Trip prep" screen are provided using the Korea Meteorological Administration’s short-term forecast service (data.go.kr).']] },
  { title: ['2. 관광 정보', '2. Tourism data'], paragraphs: [['여행지·문화·자연 정보 일부는 한국관광공사의 관광정보 서비스(공공데이터포털, data.go.kr)를 활용해 제공합니다.', 'Some place, culture, and nature information is provided using the Korea Tourism Organization’s tourism information service (data.go.kr).']] },
  { title: ['3. 음식 예시 사진', '3. Example dish photos'], paragraphs: [['"메뉴판 읽기"에서 메뉴 이름 옆에 보여드리는 음식 사진은 한국관광공사 관광사진갤러리(공공데이터포털, data.go.kr)의 자료이며, 이용허락범위에 제한이 없는 사진만 골라 씁니다. 촬영자 정보는 수집본에 함께 보관합니다.', 'The dish photos shown beside menu names in "Read a menu" come from the Korea Tourism Organization Photo Gallery (data.go.kr). We use only photos with no usage restrictions, and photographer credits are kept with our collected data.'], ['🔴 이 사진은 그 식당의 음식이 아니라 같은 이름의 음식을 보여주는 예시입니다. 화면에도 그렇게 적혀 있습니다.', 'These photos are examples of the same dish, not the food served at that restaurant. The screen says so as well.']] },
  { title: ['4. 사투리 목소리', '4. Dialect voices'], paragraphs: [['「부산 사투리 한마디」의 목소리는 타입캐스트(Typecast, typecast.ai)의 AI 음성 「개나리」·「용식이」로 만들었습니다. 사람 목소리를 흉내 낸 합성음이며, 문장은 미리 만들어 앱에 넣어 두었습니다.', 'The voices in "A word of Busan dialect" were generated with Typecast (typecast.ai) AI voices "Nari" and "Yongsik". They are synthetic voices, pre-rendered and bundled with the app.']] },
  { title: ['5. 이용 조건', '5. License'], paragraphs: [['날씨·관광 정보 두 자료는 "공공저작물 자유이용허락 표시기준 제1유형(출처표시)"에 따라 출처를 표시하고 이용합니다.', 'The weather and tourism datasets are used under the "Korea Open Government License Type 1 (Attribution)," which requires crediting the source.']] },
];
